### ISSUE TITLE
Mock API 404

### ISSUE THREAD

**Issue by whitebook** [futurice/hours-ui#21]
Hello.

I was following this nice project, I was curious why I get a 404 trying to access the mock API?

https://github.com/futurice/hours-ui-mock-api

**Comment by janivihervas** [comment]
Without knowing more, you either don't have the mock api running, or you are not running the ui with `npm run serve` or with `docker-compose`. The api is behind a reverse proxy, and that is configured only for the `webpack-dev-server` and Docker image. 

Could you try with these instructions and comment on your progress:
1. Build the Docker image for the mock api with `./dockerBuild.sh` in `hours-ui-mock-api` folder
2. Build the Docker image for the ui with `npm run docker:build` in `hours-ui` folder 
3. Run `docker-compose -p hours up -d` in `hours-ui` folder
4. Open `http://localhost` in your browser

**Comment by whitebook** [comment]
Hello!

Sorry for not being clear.
I mean I cant clone that repo. I get a 404 trying to clone. 

It gives me a 404 even if you try to view it from github.com
(Maybe it is marked as private?)

**Comment by janivihervas** [comment]
Oh! Yes it's a private repo. I didn't know if it would contain NDA stuff like customers, money etc when I started developing it so I made it private. Currently I'm on holiday and out of reach of a laptop, but I try to review the repo on next week and make it public.

**Comment by whitebook** [comment]
Thank You.

Sorry to interrupt your holiday... Enjoy the rest.
Will look for updates next week...

**Comment by janivihervas** [comment]
@whitebook sorry for the late response, I've been extremely busy lately. I reviewed the repo and everything was fine so I made it public. Happy coding and pull requests are welcome ;).
