### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by ali-rantakari** [futurice/hours-ui#25]
- Page view at about 12:50 EEST under my account
- Basically all the data is wrong in the UI
    - Incorrect hour balance (24.5 — should be 36)
    - Incorrect UTZ (88% — should be 97.3%)
    - Incorrect holiday balance (5 — should be 13)
    - "Public holiday" shown for days that are not
    - The hour markings look like they're someone else's

![screen shot 2016-10-05 at 12 52 47](https://cloud.githubusercontent.com/assets/89539/19108760/bab7a566-8afa-11e6-985e-a493fa7ab916.png)

**Comment by ali-rantakari** [comment]
Oh, is this not even supposed to display real data yet?

**Comment by ali-rantakari** [comment]
Apprently not! NEVERMIND

**Comment by phadej** [comment]
@ali-rantakari FYI, this is a public repository.
