### ISSUE TITLE
Cannot mark any hours

### ISSUE THREAD

**Issue by pahuttun** [futurice/hours-ui#46]
Can't find a way to mark hours.

Clicking "Add row" or plus symbol does nothing. No errors in the console.

(Also, should there be one row automatically when you start to mark hours to new day?)

Latest Chrome & Mac.

![image](https://cloud.githubusercontent.com/assets/4655211/23994539/03f0014c-0a4e-11e7-9521-49a4484d3f52.png)

**Comment by phadej** [comment]
The reason is the same as with, #45. But, I'm not sure why it happens: hours app doesn't know your projects, I'll check tomorrow

**Comment by phadej** [comment]
should be fixed

**Comment by pahuttun** [comment]
Fix confirmed
