### ISSUE TITLE
Has been slow, now not working at all

### ISSUE THREAD

**Issue by pahuttun** [futurice/hours-ui#49]
This issue is about performance.

The new UI has been quite slow, loading the front page for 5-10 seconds every time.

Now it seems to be totally broken giving gateway timeout:

![image](https://cloud.githubusercontent.com/assets/4655211/24547821/6d68ba7e-161a-11e7-8411-e9242828dab7.png)

Don't know if these problems have something in common

**Comment by phadej** [comment]
Our aws instances are on throttle, @mixman will  finally fix this before Monday,

**Comment by mixman** [comment]
This should now be solved.
