### ISSUE TITLE
Adding a row to an existing entry should prefill hours intelligently

### ISSUE THREAD

**Issue by pingzing** [futurice/hours-ui#66]
This is a feature that existed in the old FutuHours UI, and I'm missing it greatly in the new UI.

Previously, when adding a new row to any entry, the "Hours" dropbox would be prefilled with whatever number of hours was necessary to add up to 7.5 hours for that day. 

For example, if I marked 1 hour to the first row, adding a new row would generate a row with hours pre-filled to 6.5 hours.

**Comment by phadej** [comment]
Duplicate of #55, please comment a logic you want there.
